""" Constants file for Auth0's seed project
"""
AUTH0_CLIENT_ID = 'AUTH0_CLIENT_ID'
AUTH0_CLIENT_SECRET = 'AUTH0_CLIENT_SECRET'
AUTH0_CALLBACK_URL = 'AUTH0_CALLBACK_URL'
AUTH0_DOMAIN = 'AUTH0_DOMAIN'
AUTH0_AUDIENCE = 'AUTH0_AUDIENCE'
PROFILE_KEY = 'profile'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'

AUTH0_RESPONSE_TYPE = 'AUTH0_RESPONSE_TYPE'
AUTH0_GRANT_TYPE = 'AUTH0_GRANT_TYPE'
AUTH0_SCOPES = 'AUTH0_SCOPES'
AUTH0_CODE_CHALLENGE_METHOD = 'AUTH0_CODE_CHALLENGE_METHOD'
